### PR TITLE
Fix CMakeList missing Protobuf_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by WilliamTambellini**
Just add Protobuf_INCLUDE_DIRS to include_directories() as needed if protobuf installed in custom location.

### CODE REVIEW

**Comment by nico** [comment]
This fixes #23.

**Comment by WilliamTambellini** [comment]
@jasonriesa  Anything wrong with that PR ? It does fix building via cmake when protobuf headers not in system path. Kind.

**Comment by bzz** [comment]
Confirmed that this fixes the #23, and is usefull for an old protobuf installed with the custom prefix.

**Comment by jasonriesa** [comment]
LGTM Thanks!

**Pull request merged**
